### ISSUE TITLE
Errors when gathering data

### ISSUE THREAD

**Issue by adamyala** [csirtgadgets/bearded-avenger#124]
I'm currently using version `3.0.0a7` from the releases page. After I download the file and extract it, I `cd` into it and run `vagrant up`.

Once the box is built I `vagrant ssh` into the VM and run:
```
workon cif && cd /vagrant && 
mkdir -p log && cp hacking/develop.conf hacking/local.conf && 
cif-store -d --token-create-admin cif.yml && 
cif-store -d --token-create-hunter cif-router.yml && 
cif-store -d --token-create-smrt csirtg-smrt.yml && 
supervisord -c hacking/local.conf
```
Per [this documentation](https://github.com/csirtgadgets/bearded-avenger/wiki/Ubuntu14LTS) on deploying on Ubuntu 14.

In another tab I `vagrant ssh` into the box and run:
```
workon cif && cif -d -p && 
csirtg-smrt --config csirtg-smrt.yml -r /vagrant/rules/default -d --test
```
The help text of `scirtg-smrt` says the `-r` param can be a file or a dicrectory of files. I'd like to run all the rules so I picked the directory. After a bit of running I get the below error in the first tab, but things continue running. Is this something I should be concerned about?

```
2016-11-02 21:06:07,415 DEBG 'cif-router' stderr output:
2016-11-02 21:06:07,415 - ERROR - cif.hunter.spamhaus_ip[90][Thread-7] - All nameservers failed to answer the query 52.199.124.98.zen.spamhaus.org.5thcolumn.net. IN A: Server 127.0.0.1 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.1 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.1 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.1 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.1 UDP port 53 answered SERVFAIL

2016-11-02 21:06:07,416 DEBG 'cif-router' stderr output:
Traceback (most recent call last):
  File "/vagrant/cif/hunter/spamhaus_ip.py", line 65, in process

2016-11-02 21:06:07,420 DEBG 'cif-router' stderr output:
    r = self._resolve(i.indicator)
  File "/vagrant/cif/hunter/spamhaus_ip.py", line 59, in _resolve

2016-11-02 21:06:07,421 DEBG 'cif-router' stderr output:
    answers = dns.resolver.query(data, 'A')
  File "/home/vagrant/.virtualenvs/cif/local/lib/python2.7/site-packages/dns/resolver.py", line 1132, in query
    raise_on_no_answer, source_port)
  File "/home/vagrant/.virtualenvs/cif/local/lib/python2.7/site-packages/dns/resolver.py", line 947, in query
    raise NoNameservers(request=request, errors=errors)
NoNameservers: All nameservers failed to answer the query 52.199.124.98.zen.spamhaus.org.5thcolumn.net. IN A: Server 127.0.0.1 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.1 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.1 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.1 UDP port 53 answered The DNS operation timed out.; Server 127.0.0.1 UDP port 53 answered SERVFAIL
```
It then continues to run until I get this error in the first tab when the ssh connection closes.
```
2016-11-02 21:10:44,861 - DEBUG - cif.gatherer[45][Thread-2] - ['\x00\xbd\x1b_ ', '', 'indicators_create', '9a83236119db322cb0c1971d1d4715da16d2e18c7c5b7d1d8acb44fc9e04bdb9d3f79839711d9190', '{\n    "additional_data": null,\n    "application": "smtp",\n    "asn": null,\n    "asn_desc": null,\n    "cc": null,\n    "city": null,\n    "confidence": 6,\n    "description": "malicious host",\n    "firsttime": "2016-11-02T21:04:24.569811Z",\n    "group": "everyone",\n    "indicator": "88.249.48.81",\n    "itype": "ipv4",\n    "lasttime": "2016-11-02T21:04:24.569821Z",\n    "latitude": null,\n    "longitude": null,\n    "peers": null,\n    "portlist": 25,\n    "protocol": null,\n    "provider": "reputation.alienvault.com",\n    "rdata": null,\n    "reference": null,\n    "reference_tlp": null,\n    "reporttime": "2016-11-02T21:04:24.569785Z",\n    "tags": [\n        "malware",\n        "suspicious"\n    ],\n    "tlp": "white",\n    "version": "0.00a0"\n}']

2016-11-02 21:10:44,882 DEBG 'cif-router' stderr output:
2016-11-02 21:10:44,882 - DEBUG - cif.gatherer.asn[32][Thread-2] - "9121 | 88.249.0.0/17 | TR | ripencc | 2005-10-27"

2016-11-02 21:10:44,883 DEBG 'cif-router' stderr output:
2016-11-02 21:10:44,883 - DEBUG - cif.gatherer.geo[56][Thread-2] - 88.249.48.81
2016-11-02 21:10:44,883 - DEBUG - cif.gatherer.geo[63][Thread-2] - looking up: 88.249.48.81

2016-11-02 21:10:54,709 DEBG 'cif-router' stderr output:Connection to 127.0.0.1 closed by remote host.
Connection to 127.0.0.1 closed.
```

This happens each time I do this.

**Comment by wesyoung** [comment]
generally this means bind might not be setup correctly, data should be flowing just not getting extra data from spamhaus and putting into the db... (depends how you have bind setup, what your local network allows for udp/53 outbound, etc) but i also i want to say there are a ton of fixes in master- fix/packaging that may solve some of this too. i'm currently working on this:

https://github.com/csirtgadgets/bearded-avenger/compare/master...fix/packaging?expand=1

which is basically all the fixes + getting it all working on ubuntu/centos. hope to have a8 out in the next week or two and will test this... 

can you confirm you don't have any local network dns firewall blockers that might inhibit tcp|udp 53 traffic outbound?

**Comment by wesyoung** [comment]
also, re-try this with the latest release and the deployment scripts as a guide. it shows how we setup things like bind, etc to make things work more efficiently. closing for now, but feel free to re-open if it's still an issue...
