### ISSUE TITLE
hitting /feed with no itype param fails

### ISSUE THREAD

**Issue by JustinAzoff** [csirtgadgets/bearded-avenger#138]
```
2016-11-23 20:11:45,052 - ERROR - cif.httpd[1423][Thread-15493] - Exception on /feed [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0a10-py2.7.egg/cif/httpd/__init__.py", line 260, in feed
    f = feed_factory(filters['itype'])
KeyError: 'itype'
```

**Comment by JustinAzoff** [comment]
Also.. sending itype=dns (which is wrong because I have no idea what I am doing) does

```
2016-11-23 20:21:13,209 - ERROR - cif.httpd[1423][Thread-19991] - Exception on /feed [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0a10-py2.7.egg/cif/httpd/__init__.py", line 262, in feed
    r = f().process(r, wl)
TypeError: 'NoneType' object is not callable
```
