### ISSUE TITLE
/search exception

### ISSUE THREAD

**Issue by JustinAzoff** [csirtgadgets/bearded-avenger#167]
from trying to hit /search

```

2016-12-07 21:58:43,011 DEBG 'cif-router' stderr output:
2016-12-07 21:58:43,009 - ERROR - cif.store[161][MainThread] - handle_indicators_search() got an unexpected keyword argument 'id'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cif/store/__init__.py", line 137, in handle_message
    rv = handler(token.decode('utf-8'), data, id=id, client_id=client_id)
TypeError: handle_indicators_search() got an unexpected keyword argument 'id'


2016-12-07 21:59:26,844 DEBG 'cif-httpd' stderr output:
2016-12-07 21:59:26,840 - ERROR - cifsdk.client.zeromq[51][Thread-564] - failed
2016-12-07 21:59:26,840 - ERROR - cifsdk.client.zeromq[52][Thread-564] - NoneType
2016-12-07 21:59:26,840 - ERROR - cif.httpd[1423][Thread-564] - Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/cif/httpd/__init__.py", line 168, in search
    r = Client(remote, pull_token()).indicators_search(filters)
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/zeromq.py", line 186, in indicators_search
    rv = self._send('indicators_search', json.dumps(filters))
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/zeromq.py", line 86, in _send
    return self._recv()
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/zeromq.py", line 53, in _recv
    raise RuntimeError(data.get('message'))
RuntimeError: None

```

**Comment by JustinAzoff** [comment]
You fixed this in f7724891b0d23e098ac1b1edc34611376b0adfa1 but referenced the wrong issue
