### ISSUE TITLE
problem: string does not support the buffer interface error in Msg() class

### ISSUE THREAD

**Issue by tk-hendrik** [csirtgadgets/bearded-avenger#186]
Hi Wes,

running on commit  777b23f8e1963e947a232dd94a0a25483edc1aba
Did already update all requirements but hitting some TraceBacks like that one below.

My actual workaround would be to `token = token.encode()` - but IIRC this is a compatibility thing between python2.7.x and python3.
Also there is code in bearded-avenger-sdk....msg.py that already would do some encode('utf-8) things.

Your thoughts?

```
2016-12-16 12:26:26,654 - DEBUG - cif.router[191][MainThread] - []
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0a13+8.g777b23f.dirty-py2.7.egg/cif/router.py", line 185, in handle_message
    handler(id, mtype, token, data)
  File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0a13+8.g777b23f.dirty-py2.7.egg/cif/router.py", line 198, in handle_message_default
    Msg(id=id, mtype=mtype, token=token, data=data).send(self.store_s)
  File "build/bdist.linux-x86_64/egg/cifsdk/msg.py", line 127, in send
    s.send_multipart(m)
  File "/usr/local/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 363, in send_multipart
    i, rmsg,
TypeError: Frame 2 (u'44362366b47d27cff8bf53e8e8471c...) does not support the buffer interface.
```

[UPDATE]
'token' in my case is a type unicode which is not handled correctly in sdk.

```
>>> unitoken = u'1234'
>>> type(unitoken)
<type 'unicode'>

>>> stringtoken = '5678'
>>> type(stringtoken)
<type 'str'>

>>> type(stringtoken.encode('utf-8'))
<type 'str'>

>>> type(unitoken.encode('utf-8'))
<type 'str'>
```

**Comment by tk-hendrik** [comment]
Just a throw - after this patch all works like a charm.

```
diff --git a/cifsdk/msg.py b/cifsdk/msg.py
index 071b05a..37490c3 100644
--- a/cifsdk/msg.py
+++ b/cifsdk/msg.py
@@ -95,6 +95,8 @@ class Msg(object):
         if self.token:
             if isinstance(self.token, str):
                 self.token = self.token.encode('utf-8')
+            if isinstance(self.token, unicode):
+                self.token = self.token.encode('utf-8')
 
             m.append(self.token)
 
```

**Comment by wesyoung** [comment]
i've been fighting through a few of these as we've abstracted them out, mind throwing a PR over to:

https://github.com/csirtgadgets/bearded-avenger-sdk-py

https://github.com/csirtgadgets/bearded-avenger-sdk-py/blob/master/cifsdk/msg.py#L95
