### ISSUE TITLE
problem: doc needs some work; too confusing.

### ISSUE THREAD

**Issue by ventz** [csirtgadgets/bearded-avenger#251]
Following steps here:
https://github.com/csirtgadgets/bearded-avenger/wiki

Once you get to:
```
csirtg-smrt --config csirtg-smrt.yml --test -r rules/default/csirtg.yml -d
```

It fails with (once you remove "--test"):
```
# csirtg-smrt --config csirtg-smrt.yml -r bearded-avenger/rules/default/csirtg.yml -d
2017-02-15 16:04:26,322 - INFO - csirtg_smrt.smrt[337] - loglevel is: DEBUG
2017-02-15 16:04:26,325 - DEBUG - csirtg_smrt.smrt[106] - processing bearded-avenger/rules/default/csirtg.yml
2017-02-15 16:04:26,333 - DEBUG - csirtg_smrt.fetcher[67] - /tmp/smrt/csirtg.io
2017-02-15 16:04:26,334 - DEBUG - csirtg_smrt.fetcher[86] - CACHE /tmp/smrt/csirtg.io/uce-urls.csv
2017-02-15 16:04:26,335 - DEBUG - csirtg_smrt.smrt[138] - loading parser: <class 'zcsv.Csv'>
2017-02-15 16:04:26,336 - DEBUG - csirtg_smrt.fetcher[140] - ['wget', '--header', 'User-Agent: csirtg-smrt/0.0.0a22 (csirtgadgets.org)', '--timeout=120', 'https://csirtg.io/api/users/csirtgadgets/feeds/uce-urls.csv', '-N', '-P', '/tmp/smrt/csirtg.io']
Traceback (most recent call last):
  File "/usr/local/bin/csirtg-smrt", line 9, in <module>
    load_entry_point('csirtg-smrt', 'console_scripts', 'csirtg-smrt')()
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 359, in main
    'goback': goback
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 252, in _run_smrt
    for i in s.process(r, f, limit=args.limit, data=data, filters=filters):
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 212, in process
    for indicator_batch in feed_indicators_batches:
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/utils/__init__.py", line 92, in chunk
    for x in it:
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 208, in <genexpr>
    feed_indicators = (i for i in feed_indicators if not self.is_archived_with_log(i))
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 202, in <genexpr>
    feed_indicators = (self.clean_indicator(i, rule) for i in feed_indicators)
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/parser/delim.py", line 20, in process
    for l in self.fetcher.process():
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/fetcher.py", line 151, in process
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

But if you download and run requirements here:
https://github.com/csirtgadgets/csirtg-smrt-py/blob/master/requirements.txt

It works (without --test, since that seems removed).

**Comment by ventz** [comment]
Found a few other issues.

* Looks like part of this is a duplicate pages with instructions which are slightly different.

* Possibly expanding the:
```
This assumes you have a proper Python dev already environment properly configured.
```
(here: https://github.com/csirtgadgets/bearded-avenger/wiki)

* The last bit is the package requirement "supervisor" (which is obvious/easy, but not in the steps anywhere, so install/run fails).

* Having pip upgraded helps in one other case too.

**Comment by wesyoung** [comment]
what release are you testing with?
are you trying to build from just the source? or are you using one of the easybutton guides [from the right hand of the page] ?

**Comment by ventz** [comment]
@wesyoung I was testing with the latest "bearded-avenger" (for 16.04 LTS)

Steps here: https://github.com/csirtgadgets/bearded-avenger
vs
here: https://github.com/csirtgadgets/bearded-avenger/wiki

A little bit different. The main one (github) seems to have the --test missing, and the requirements is not enough.

Using the latest dev-release worked however (as long as pip is ugpraded + wget is added, and supervisor is installed):
https://github.com/csirtgadgets/bearded-avenger/archive/3.0.0a15.tar.gz

**Comment by wesyoung** [comment]
did you try this?

https://github.com/csirtgadgets/bearded-avenger/wiki/Ubuntu16LTS

which configures the underlying issues i think you're running into(?)

**Comment by ventz** [comment]
@wesyoung Thanks. I got it work at this point with the other steps too, but that looks easier/better.

By the way, take a look at irc ;) --> i'll remove this comment after it generates an email/ping for you.

**Comment by wesyoung** [comment]
"master" may be a little out of whack atm [and most times] as we iterate things (csirtg-smrt, csirtg-indicator, etc). so things from "master" may not always install properly, but things with release tags should at-least always work "out of the box" when we do our end to end testing (before we tag).

actually doing that now; hope to have another release that removes that wget req soon (re-wrote it via requests instead doing our own smrt caching of the feed data).

trying to clean up the doc a bit too; i understand it can be confusing...

**Comment by wesyoung** [comment]
i try to avoid IRC at all costs. :)

(things just tend to get lost)

**Comment by newconf** [comment]
Hi, 
Regarding docs, I think that it would be better to mention somewhere the inputs/outputs of the tool, so that future users can be encouraged to use/enrich it.
I have to do a survey on different threat intelligence tools, but I need some more information about CIF v3 to do it correctly.
Please can you enlighten me on the different input formats supported by CIF v3 (STIX, CyBOX)? 
Many thanks!

**Comment by wesyoung** [comment]
tied to: https://github.com/csirtgadgets/bearded-avenger/issues/62
