### ISSUE TITLE
2017-02-16 02:32:59,239 - ERROR - cifsdk.client.http[114] - submission failed

### ISSUE THREAD

**Issue by solower** [csirtgadgets/bearded-avenger#252]
$>csirtg-smrt --client cif --fireball -r  /etc/cif/rules/default/openphish.yml -d
........
........
2017-02-16 02:32:59,239 - ERROR - cifsdk.client.http[114] - submission failed
Traceback (most recent call last):
  File "/usr/local/bin/csirtg-smrt", line 11, in <module>
    load_entry_point('csirtg-smrt==0.0.0a22', 'console_scripts', 'csirtg-smrt')()
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 359, in main
    'goback': goback
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 252, in _run_smrt
    for i in s.process(r, f, limit=args.limit, data=data, filters=filters):
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 214, in process
    self.send_indicators(indicator_batch)
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 190, in send_indicators
    self.client.indicators_create(indicators)
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/http.py", line 182, in indicators_create
    rv = self._post(uri, data)
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/http.py", line 115, in _post
    raise RuntimeError(err)
RuntimeError: submission failed

**Comment by wesyoung** [comment]
i think this was a known issue; and i just pushed a new release that i think fixes this:

https://github.com/csirtgadgets/bearded-avenger/releases/tag/3.0.0a16

gonna close for now; if you see it again, we'll re-open..
