### ISSUE TITLE
BIND format output error

### ISSUE THREAD

**Issue by ventz** [csirtgadgets/bearded-avenger#264]
Noticing this:

```
$ cif --itype fqdn --feed --format bind
Traceback (most recent call last):
  File "/usr/local/bin/cif", line 9, in <module>
    load_entry_point('cifsdk==3.0.0a20', 'console_scripts', 'cif')()
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/client.py", line 176, in main
    print(FORMATS[options.get('format')](data=rv))
  File "/usr/local/lib/python2.7/dist-packages/csirtg_indicator/format/zbind.py", line 39, in __repr__
    if i.itype is not 'fqdn':
AttributeError: 'dict' object has no attribute 'itype'

$ cif --itype ipv4 --feed --format bind
Traceback (most recent call last):
  File "/usr/local/bin/cif", line 9, in <module>
    load_entry_point('cifsdk==3.0.0a20', 'console_scripts', 'cif')()
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/client.py", line 176, in main
    print(FORMATS[options.get('format')](data=rv))
  File "/usr/local/lib/python2.7/dist-packages/csirtg_indicator/format/zbind.py", line 39, in __repr__
    if i.itype is not 'fqdn':
AttributeError: 'dict' object has no attribute 'itype'

$ cif --itype url --feed --format bind
Traceback (most recent call last):
  File "/usr/local/bin/cif", line 9, in <module>
    load_entry_point('cifsdk==3.0.0a20', 'console_scripts', 'cif')()
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/client.py", line 176, in main
    print(FORMATS[options.get('format')](data=rv))
  File "/usr/local/lib/python2.7/dist-packages/csirtg_indicator/format/zbind.py", line 39, in __repr__
    if i.itype is not 'fqdn':
AttributeError: 'dict' object has no attribute 'itype'
```

Unrelated, but similar - if you give it --feed, with something like snort/bind/etc, it produces an error. This makes sense, but the error looks like a crash, rather than an error along the lines of: "it doesn't make sense to request this, possibly try ..."

**Comment by ventz** [comment]
@wesyoung I was able to fix the plugin -- I'll submit a PR :)

**Comment by ventz** [comment]
Creating this issue for the appropriate repo and moving there: https://github.com/csirtgadgets/csirtg-indicator-py/issues/81
