### ISSUE TITLE
The 'cifsdk' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by bstlee0** [csirtgadgets/bearded-avenger#281]
Working on Ubuntu16.04.  I'm running into this issue with bash easybutton.sh.

```
giving things a chance to settle...
testing connectivity
Traceback (most recent call last):
  File "/usr/local/bin/cif", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cifsdk' distribution was not found and is required by the application
```

I've confirmed that the following was installed
```
 sudo apt-get install -y python-dev python-pip git
 pip install cifsdk
```
These commands were ran as root.  What am I doing wrong?

**Comment by wesyoung** [comment]
what release are you testing with?
can you provide a copy of the install logs?
