### ISSUE TITLE
 ERROR - cif.store[173][MainThread] - 'NoneType' object has no attribute 'filter'

### ISSUE THREAD

**Issue by jbilder** [csirtgadgets/bearded-avenger#283]
Quite frequently, the cif-router service is experiencing issues storing data.  I've been scouring google with little success.  Any assistance is much appreciated:

2017-04-10 15:43:36,162 - ERROR - cif.store[173][MainThread] - 'NoneType' object has no attribute 'filter'
Traceback (most recent call last):
  File "/home/ubuntu/bearded-avenger/cif/store/__init__.py", line 155, in handle_message
    rv = handler(token, data, id=id, client_id=client_id)
  File "/home/ubuntu/bearded-avenger/cif/store/__init__.py", line 215, in handle_indicators_create
    r = self.store.indicators.upsert(t, data)
  File "/home/ubuntu/bearded-avenger/cif/store/zelasticsearch/indicator.py", line 173, in upsert
    rv = list(self.search(token, filters, sort='reporttime', raw=True))
  File "/home/ubuntu/bearded-avenger/cif/store/zelasticsearch/indicator.py", line 316, in search
    s = self._filters_build(filters, s)
  File "/home/ubuntu/bearded-avenger/cif/store/zelasticsearch/indicator.py", line 293, in _filters_build
    s = self._filter_terms(q_filters, s)
  File "/home/ubuntu/bearded-avenger/cif/store/zelasticsearch/indicator.py", line 277, in _filter_terms
    s = s.filter('terms', **kwargs)
AttributeError: 'NoneType' object has no attribute 'filter'

**Comment by wesyoung** [comment]
what release are you testing with?

**Comment by jbilder** [comment]
Thanks for responding, Wes.  I followed the documented created for Ubuntu 16.04 LTS.

**Comment by wesyoung** [comment]
err what release of bearded-avenger:

https://github.com/csirtgadgets/bearded-avenger/releases

haven't done a TON of debugging of ES, so may need to [write up an FAQ for] turn on some debugging info by turning on `CIF_STORE_ES_TRACE=1 cif-router -d ...` in your local env... get some context around the error.

do you have cif-httpd logs from around this timeframe too?
