### ISSUE TITLE
problem: httpd timeouts (zmq)

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/bearded-avenger#287]
zmq timeouts too short for --feed pulls (which are > 30s). make it 90s ?

```
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: 2017-04-17 19:40:57,556 - ERROR - cif.httpd[1423][Thread-1340] - Exception on /feed [GET]
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: Traceback (most recent call last):
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: response = self.full_dispatch_request()
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: rv = self.handle_user_exception(e)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: reraise(exc_type, exc_value, tb)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: rv = self.dispatch_request()
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: return self.view_functions[rule.endpoint](**req.view_args)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib/python2.7/site-packages/flask/views.py", line 84, in view
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: return self.dispatch_request(*args, **kwargs)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: return meth(*args, **kwargs)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib/python2.7/site-packages/cif-3.0.0a17+11.gad1114b.dirty-py2.7.egg/cif/httpd/views/feed/__init__.py", line 76, in get
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: r = Client(remote, pull_token()).indicators_search(filters)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib/python2.7/site-packages/cifsdk/client/zeromq.py", line 166, in indicators_search
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: return self._send(Msg.INDICATORS_SEARCH, json.dumps(filters), decode=decode)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib/python2.7/site-packages/cifsdk/client/zeromq.py", line 84, in _send
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: return self._recv(decode=decode)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib/python2.7/site-packages/cifsdk/client/zeromq.py", line 48, in _recv
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: mtype, data = Msg().recv(self.socket)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib/python2.7/site-packages/cifsdk/msg.py", line 72, in recv
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: m = s.recv_multipart()
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib64/python2.7/site-packages/zmq/sugar/socket.py", line 395, in recv_multipart
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: parts = [self.recv(flags, copy=copy, track=track)]
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7683)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7460)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "zmq/backend/cython/socket.pyx", line 150, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2437)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2344)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9823)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: raise Again(errno)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: Again: Resource temporarily unavailable
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: 2017-04-17 19:40:57,618 - INFO - werkzeug[87][Thread-1340] - 127.0.0.1 - - [17/Apr/2017 19:40:57] "GET /feed?itype=ipv4&tags=scanner&confidence=8&nolog=False&days=21&limit=50 HTTP/1.1" 500 -
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: Traceback (most recent call last):
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: self.finish_request(request, client_address)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: self.RequestHandlerClass(request, client_address, self)
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib64/python2.7/SocketServer.py", line 651, in __init__
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: self.finish()
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib64/python2.7/SocketServer.py", line 710, in finish
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: self.wfile.close()
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib64/python2.7/socket.py", line 279, in close
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: self.flush()
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: File "/usr/lib64/python2.7/socket.py", line 303, in flush
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: self._sock.sendall(view[write_offset:write_offset+buffer_size])
Apr 17 19:40:57 localhost.localdomain cif-httpd[4752]: error: [Errno 32] Broken pipe
```

**Comment by wesyoung** [comment]
```
Apr 21 12:30:33 ip-172-31-7-76 cif-httpd[19532]: 2017-04-21 12:30:33,680 - DEBUG - cif-httpd[64][Thread-3012] - content-length: 17015
Apr 21 12:30:33 ip-172-31-7-76 cif-httpd[19532]: 2017-04-21 12:30:33,680 - INFO - cif-httpd[66][Thread-3012] - fireball mode
Apr 21 12:30:40 ip-172-31-7-76 cif-httpd[19532]: 2017-04-21 12:30:40,501 - INFO - werkzeug[87][Thread-3012] - 127.0.0.1 - - [21/Apr/2017 12:30:40] "POST /indicators HTTP/1.1" 201 -
Apr 21 12:38:01 ip-172-31-7-76 cif-httpd[19532]: 2017-04-21 12:38:01,589 - INFO - werkzeug[87][Thread-3014] - 127.0.0.1 - - [21/Apr/2017 12:38:01] "GET /ping HTTP/1.1" 200 -
Apr 21 12:38:02 ip-172-31-7-76 cif-httpd[19532]: 2017-04-21 12:38:02,848 - INFO - werkzeug[87][Thread-3016] - 127.0.0.1 - - [21/Apr/2017 12:38:02] "GET /ping HTTP/1.1" 200 -
Apr 21 12:38:04 ip-172-31-7-76 cif-httpd[19532]: 2017-04-21 12:38:04,865 - INFO - werkzeug[87][Thread-3018] - 127.0.0.1 - - [21/Apr/2017 12:38:04] "GET /ping HTTP/1.1" 200 -
Apr 21 12:38:19 ip-172-31-7-76 cif-httpd[19532]: 2017-04-21 12:38:19,907 - INFO - werkzeug[87][Thread-3020] - 127.0.0.1 - - [21/Apr/2017 12:38:19] "GET /feed?itype=ipv4&tags=scanners&confidence=8&nolog=False&days=21&limit=50000 HTTP/1.1" 200 -
Apr 21 12:38:30 ip-172-31-7-76 cif-httpd[19532]: 2017-04-21 12:38:30,042 - INFO - werkzeug[87][Thread-3022] - 127.0.0.1 - - [21/Apr/2017 12:38:30] "GET /feed?itype=ipv4&tags=scanners&confidence=8&nolog=False&days=21&limit=50000 HTTP/1.1" 200 -
Apr 21 12:38:34 ip-172-31-7-76 cif-httpd[19532]: 2017-04-21 12:38:34,084 - INFO - werkzeug[87][Thread-3024] - 127.0.0.1 - - [21/Apr/2017 12:38:34] "GET /feed?itype=ipv4&tags=scanners&confidence=5&nolog=False&days=21&limit=50000 HTTP/1.1" 200 -
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]: 2017-04-21 12:40:12,101 - ERROR - cif.httpd[1423][Thread-3026] - Exception on /feed [GET]
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]: Traceback (most recent call last):
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:     response = self.full_dispatch_request()
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:     rv = self.handle_user_exception(e)
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:     reraise(exc_type, exc_value, tb)
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:     rv = self.dispatch_request()
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:     return self.dispatch_request(*args, **kwargs)
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:     return meth(*args, **kwargs)
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/cif-refs_pull_285_head-py2.7.egg/cif/httpd/views/feed/__init__.py", line 76, in get
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:     r = Client(remote, pull_token()).indicators_search(filters)
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/zeromq.py", line 166, in indicators_search
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:     return self._send(Msg.INDICATORS_SEARCH, json.dumps(filters), decode=decode)
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/zeromq.py", line 84, in _send
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:     return self._recv(decode=decode)
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/zeromq.py", line 48, in _recv
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:     mtype, data = Msg().recv(self.socket)
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/cifsdk/msg.py", line 72, in recv
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:     m = s.recv_multipart()
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 395, in recv_multipart
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:     parts = [self.recv(flags, copy=copy, track=track)]
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7683)
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7460)
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "zmq/backend/cython/socket.pyx", line 150, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2437)
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2344)
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:   File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9823)
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]:     raise Again(errno)
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]: Again: Resource temporarily unavailable
Apr 21 12:40:12 ip-172-31-7-76 cif-httpd[19532]: 2017-04-21 12:40:12,111 - INFO - werkzeug[87][Thread-3026] - 127.0.0.1 - - [21/Apr/2017 12:40:12] "GET /feed?itype=ipv4&tags=scanner&confidence=5&nolog=False&days=21&limit=50000 HTTP/1.1" 500 -
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]: 2017-04-21 12:41:51,713 - ERROR - cif.httpd[1423][Thread-3028] - Exception on /feed [GET]
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]: Traceback (most recent call last):
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     response = self.full_dispatch_request()
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     rv = self.handle_user_exception(e)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     reraise(exc_type, exc_value, tb)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     rv = self.dispatch_request()
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     return self.dispatch_request(*args, **kwargs)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     return meth(*args, **kwargs)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/cif-refs_pull_285_head-py2.7.egg/cif/httpd/views/feed/__init__.py", line 76, in get
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     r = Client(remote, pull_token()).indicators_search(filters)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/zeromq.py", line 166, in indicators_search
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     return self._send(Msg.INDICATORS_SEARCH, json.dumps(filters), decode=decode)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/zeromq.py", line 84, in _send
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     return self._recv(decode=decode)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/zeromq.py", line 48, in _recv
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     mtype, data = Msg().recv(self.socket)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/cifsdk/msg.py", line 72, in recv
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     m = s.recv_multipart()
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/local/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 395, in recv_multipart
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     parts = [self.recv(flags, copy=copy, track=track)]
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7683)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:7460)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "zmq/backend/cython/socket.pyx", line 150, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2437)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:2344)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:9823)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     raise Again(errno)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]: Again: Resource temporarily unavailable
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]: 2017-04-21 12:41:51,714 - INFO - werkzeug[87][Thread-3028] - 127.0.0.1 - - [21/Apr/2017 12:41:51] "GET /feed?itype=ipv4&tags=scanner&confidence=5&nolog=False&days=21&limit=25 HTTP/1.1" 500 -
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]: Traceback (most recent call last):
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     self.finish_request(request, client_address)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     self.RequestHandlerClass(request, client_address, self)
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     self.finish()
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     self.wfile.close()
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/lib/python2.7/socket.py", line 283, in close
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     self.flush()
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:   File "/usr/lib/python2.7/socket.py", line 307, in flush
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
Apr 21 12:41:51 ip-172-31-7-76 cif-httpd[19532]: error: [Errno 32] Broken pipe
```

**Comment by wesyoung** [comment]
the router never unblocks from cif-store when a req times out. so the router stops answering q's.
