### ISSUE TITLE
problem: es race condition

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/bearded-avenger#321]
happens during health checks...

```
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]: Process Process-2:
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]: Traceback (most recent call last):
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:     self.run()
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:     self._target(*self._args, **self._kwargs)
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:   File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0a21-py2.7.egg/cif/store/__init__.py", line 120, in start
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:     self.handle_message(m)
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:   File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0a21-py2.7.egg/cif/store/__init__.py", line 194, in handle_message
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:     self.store.tokens.update_last_activity_at(token, arrow.utcnow().datetime)
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:   File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0a21-py2.7.egg/cif/store/zelasticsearch/token.py", line 121, in update_last_activity_at
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:     rv.update(last_activity_at=timestamp)
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/document.py", line 374, in update
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:     **doc_meta
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:     return func(*args, params=params, **kwargs)
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 527, in update
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:     doc_type, id, '_update'), params=params, body=body)
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 318, in perform_request
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:     self._raise_error(response.status, raw_data)
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 124, in _raise_error
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]:     raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
Jun 09 15:13:18 ip-172-31-5-173 cif-router[1771]: ConflictError: TransportError(409, u'version_conflict_engine_exception', u'[token][AVyNJsBXmsNrRaOTUZT-]: version conflict, current version [9] is different than the one provided [8]')
```

**Comment by wesyoung** [comment]
http://elasticsearch-py.readthedocs.io/en/master/api.html?highlight=retry_on#elasticsearch.Elasticsearch.update

**Comment by wesyoung** [comment]
also; when this crashes, cif-router doesn't come back?
