### ISSUE TITLE
CIF Router Timeouts

### ISSUE THREAD

**Issue by coonsmatthew** [csirtgadgets/bearded-avenger#419]
## Do you have an active https://csirtg.io/support account ? :)
No

## Expected behavior and actual behavior.
I just installed CIFv3, after installation, queries were working for a few hours, but after that they stopped working. 

I'm getting a "http timeout" error, which would lead me to believe that CIF-Router is either not getting the requests or is too busy to respond. 

I thought this may be caused by a firewall, but I also disabled the local firewall without any change in behavior. 

## Steps to reproduce the problem

```
user@host:/usr/local/share/GeoIP$ cif -d -p
2018-09-18 14:18:31,566 - INFO - cifsdk.client.client[136][MainThread] - running ping
2018-09-18 14:18:31,568 - DEBUG - urllib3.connectionpool[205][MainThread] - Starting new HTTP connection (1): localhost:5000
Traceback (most recent call last):
  File "/usr/local/bin/cif", line 11, in <module>
    load_entry_point('cifsdk==3.0.0', 'console_scripts', 'cif')()
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/client.py", line 143, in main
    ret = cli.ping()
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/http.py", line 229, in ping
    rv = self._get(uri)
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/http.py", line 88, in _get
    resp = self.session.get(uri, params=params, verify=self.verify_ssl, timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=5000): Read timed out. (read timeout=120)
```

### Gunicorn log: 

```
Sep 18 14:13:47 host gunicorn[12246]: [2018-09-18 14:13:47,324] ERROR in app: Exception on /ping [GET]
Sep 18 14:13:47 host gunicorn[12246]: Traceback (most recent call last):
Sep 18 14:13:47 host gunicorn[12246]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
Sep 18 14:13:47 host gunicorn[12246]:     response = self.full_dispatch_request()
Sep 18 14:13:47 host gunicorn[12246]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
Sep 18 14:13:47 host gunicorn[12246]:     rv = self.handle_user_exception(e)
Sep 18 14:13:47 host gunicorn[12246]:   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
Sep 18 14:13:47 host gunicorn[12246]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Sep 18 14:13:47 host gunicorn[12246]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
Sep 18 14:13:47 host gunicorn[12246]:     reraise(exc_type, exc_value, tb)
Sep 18 14:13:47 host gunicorn[12246]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
Sep 18 14:13:47 host gunicorn[12246]:     rv = self.dispatch_request()
Sep 18 14:13:47 host gunicorn[12246]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
Sep 18 14:13:47 host gunicorn[12246]:     return self.view_functions[rule.endpoint](**req.view_args)
Sep 18 14:13:47 host gunicorn[12246]:   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
Sep 18 14:13:47 host gunicorn[12246]:     return self.dispatch_request(*args, **kwargs)
Sep 18 14:13:47 host gunicorn[12246]:   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 149, in dispatch_request
Sep 18 14:13:47 host gunicorn[12246]:     return meth(*args, **kwargs)
Sep 18 14:13:47 host gunicorn[12246]:   File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0rc5-py2.7.egg/cif/httpd/views/ping.py", line 24, in get
Sep 18 14:13:47 host gunicorn[12246]:     r = Client(remote, pull_token()).ping(write=write)
Sep 18 14:13:47 host gunicorn[12246]:   File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/zeromq.py", line 110, in ping
Sep 18 14:13:47 host gunicorn[12246]:     return self._send(Msg.PING_WRITE)
Sep 18 14:13:47 host gunicorn[12246]:   File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/zeromq.py", line 106, in _send
Sep 18 14:13:47 host gunicorn[12246]:     return self._recv(decode=decode)
Sep 18 14:13:47 host gunicorn[12246]:   File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/zeromq.py", line 53, in _recv
Sep 18 14:13:47 host gunicorn[12246]:     mtype, data = Msg().recv(self.socket)
Sep 18 14:13:47 host gunicorn[12246]:   File "/usr/local/lib/python2.7/dist-packages/cifsdk/msg.py", line 72, in recv
Sep 18 14:13:47 host gunicorn[12246]:     m = s.recv_multipart()
Sep 18 14:13:47 host gunicorn[12246]:   File "/usr/local/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 395, in recv_multipart
Sep 18 14:13:47 host gunicorn[12246]:     parts = [self.recv(flags, copy=copy, track=track)]
Sep 18 14:13:47 host gunicorn[12246]:   File "zmq/backend/cython/socket.pyx", line 693, in zmq.backend.cython.socket.Socket.recv
Sep 18 14:13:47 host gunicorn[12246]:   File "zmq/backend/cython/socket.pyx", line 727, in zmq.backend.cython.socket.Socket.recv
Sep 18 14:13:47 host gunicorn[12246]:   File "zmq/backend/cython/socket.pyx", line 150, in zmq.backend.cython.socket._recv_copy
Sep 18 14:13:47 host gunicorn[12246]:   File "zmq/backend/cython/socket.pyx", line 145, in zmq.backend.cython.socket._recv_copy
Sep 18 14:13:47 host gunicorn[12246]:   File "zmq/backend/cython/checkrc.pxd", line 19, in zmq.backend.cython.checkrc._check_rc
Sep 18 14:13:47 host gunicorn[12246]:     raise Again(errno)
Sep 18 14:13:47 host gunicorn[12246]: Again: Resource temporarily unavailable
```

## Specifications like the version of the project, operating system, or hardware.

- 4 cores/8gb of ram
- Ubuntu 16.04.5 LTS

**Comment by coonsmatthew** [comment]
Also, if this is a SQLite issue, I will gladly move to ES if it will fix my problem.

**Comment by coonsmatthew** [comment]
IT seems like this may just be an SQLite? issue as things work great for a bit, and then slow down again. I can make queries without any issues, but randomly I will start noticing that queries start hanging.

**Comment by coonsmatthew** [comment]
I've decided to move to ES 👍
